import type {GabaVideoRecord} from './gabaVideos';

// Public-safe video records only. The detailed titles, claims, and monitoring
// candidates stay in the presenter-only chunk loaded by presenter mode.
const sharedVideos: GabaVideoRecord[] = [
  {
    id: 'SHORT-08',
    title: 'GABA의 역할을 묻는 영상 후보',
    publicTitle: 'GABA의 역할을 묻는 영상 후보',
    publicSummary: 'GABA가 어떤 역할을 하는지 묻고 설명하는 영상 후보입니다. 일반 생리 설명과 개인 조언은 구분해 확인합니다.',
    publicPersonSummary: '화자의 소속·경력 확인 출처가 있으나, 영상 속 실제 발언과 근거의 범위를 대신 확인하지는 않습니다.',
    publicOperatorSentence: 'GABA의 일반 역할 설명을 원문·자막·화자 확인 후 일반 교육 자료로 사용할 수 있는지 판단합니다.',
    url: 'https://www.youtube.com/shorts/4xGSHxkMYew',
    previewImage: 'https://i.ytimg.com/vi/4xGSHxkMYew/hqdefault.jpg',
    previewAlt: 'GABA의 역할을 묻는 영상 후보 미리보기',
    previewLabel: 'YouTube Shorts · 오늘 공유 영상',
    channel: '비엠한방내과 공식 채널',
    sourceChannelUrl: 'https://www.youtube.com/@bm_k_clinic',
    speaker: '공개 프로필 확인 필요',
    authorityEvidenceUrl: 'https://www.bmkclinic.com/bm-posts/a-scientists-perspective---bm-k-clinic-director-lee-je-wons-akomnews-interview',
    summary: 'GABA의 일반 역할을 묻고 설명하는 영상 후보입니다. 정확한 내용과 맥락은 원문 확인이 필요합니다.',
    operatorSentence: '일반 역할 설명과 개인 조언을 분리해 원문·자막·화자 확인 후 사용 범위를 판단합니다.',
    personSummary: '공개 프로필은 화자의 소속·경력 확인에 참고할 수 있으나, 영상 발언의 근거와 범위를 자동 승인하지 않습니다.',
    status: 'LIMITED_USE',
    statusReason: '일반 역할 설명과 개인 조언을 원문·자막·화자 확인 전에는 구분할 수 없습니다.',
    checkedAt: '2026-09-22',
    audit: {contentBasis: 'TITLE_AND_PUBLIC_DESCRIPTION', authorityLevel: 'PARTIAL', evidenceLevel: 'C', claimCategories: ['GENERAL_PHYSIOLOGY'], rightsStatus: 'CHECK_REQUIRED', usageMode: 'REVIEW_ONLY', nextAction: '자격·실제 화자와 일반 역할 설명 구간을 먼저 확인'},
  },
  {
    id: 'SHORT-04',
    title: 'GABA의 일반 역할을 소개하는 영상 후보',
    publicTitle: 'GABA의 일반 역할을 소개하는 영상 후보',
    publicSummary: 'GABA를 뇌의 신호 조절과 연결해 설명하는 영상 후보입니다. 일반 생리 설명과 그 밖의 주장은 구분해 확인합니다.',
    publicPersonSummary: '관련 의료기관 출처가 있으나, 그 출처가 실제 영상 화자·발언·근거의 범위를 자동으로 확인해 주지는 않습니다.',
    publicOperatorSentence: 'GABA의 일반 정의·기능에 해당하는 구간만 원문과 자막으로 확인한 뒤 사용 범위를 판단합니다.',
    url: 'https://www.youtube.com/shorts/BiZXS_ojLUA',
    previewImage: 'https://i.ytimg.com/vi/BiZXS_ojLUA/hqdefault.jpg',
    previewAlt: 'GABA의 일반 역할을 소개하는 영상 후보 미리보기',
    previewLabel: 'YouTube Shorts · 오늘 공유 영상',
    channel: '브레인튜브 공식 채널',
    sourceChannelUrl: 'https://www.youtube.com/@%EB%B8%8C%EB%A0%88%EC%9D%B8%ED%8A%9C%EB%B8%8CBrainDoctor',
    speaker: '실제 화자 확인 필요',
    authorityEvidenceUrl: 'https://www.youtube.com/@%EB%B8%8C%EB%A0%88%EC%9D%B8%ED%8A%9C%EB%B8%8CBrainDoctor/about',
    summary: 'GABA를 뇌의 신호 조절과 연결해 설명하는 영상 후보입니다. 일반 생리 설명과 그 밖의 주장은 구분해 확인합니다.',
    operatorSentence: '일반 GABA 정의 구간만 원문·자막·화자 확인 후 제한적으로 검토합니다.',
    personSummary: '공식 채널 프로필은 인물·소속 확인에 참고할 수 있으나, 영상의 실제 발언과 근거를 독립적으로 승인하지 않습니다.',
    status: 'LIMITED_USE',
    statusReason: '일반 GABA 정의 구간을 자막·타임코드·실제 화자 확인 후 검토해야 합니다.',
    checkedAt: '2026-09-22',
    audit: {contentBasis: 'TITLE_AND_PUBLIC_DESCRIPTION', authorityLevel: 'PARTIAL', evidenceLevel: 'B', claimCategories: ['GENERAL_PHYSIOLOGY', 'SLEEP_STRESS'], rightsStatus: 'CHECK_REQUIRED', usageMode: 'REVIEW_ONLY', nextAction: '일반 정의 구간의 자막·타임코드·실제 화자를 확인'},
  },
  {
    id: 'SHORT-05',
    title: '음식과 GABA의 관계를 설명하는 영상 후보',
    publicTitle: '음식과 GABA의 관계를 설명하는 영상 후보',
    publicSummary: '음식과 GABA 성분의 관계를 설명하는 방식의 영상입니다. 음식 속 성분과 사람에게 나타나는 결과는 따로 확인합니다.',
    publicPersonSummary: '화자의 소속·경력 확인 출처가 있으나, 영상 발언과 GABA 연구 근거를 자동 승인하는 자료는 아닙니다.',
    publicOperatorSentence: '음식 속 GABA와 일반 인체 연구를 구분해 원문·자막·근거를 확인합니다.',
    url: 'https://www.youtube.com/shorts/7Zsxm9Wh2Yg',
    previewImage: 'https://i.ytimg.com/vi/7Zsxm9Wh2Yg/hqdefault.jpg',
    previewAlt: '음식과 GABA의 관계를 설명하는 영상 후보 미리보기',
    previewLabel: 'YouTube Shorts · 오늘 공유 영상',
    channel: '30년 자율신경, 정이안한의원TV',
    sourceChannelUrl: 'https://www.youtube.com/@JeongianTV',
    speaker: '공개 프로필 확인 필요',
    authorityEvidenceUrl: 'https://mediahub.seoul.go.kr/archives/1135642',
    summary: '음식과 GABA 성분의 관계를 설명하는 영상 후보입니다. 음식 속 성분과 사람에게 나타나는 결과는 따로 확인합니다.',
    operatorSentence: '음식 속 GABA와 일반 인체 연구를 구분해 원문·자막·근거를 확인합니다.',
    personSummary: '공개 프로필은 화자의 소속·경력 확인에 참고할 수 있으나, 영상 발언과 연구 근거를 자동 승인하지 않습니다.',
    status: 'LIMITED_USE',
    statusReason: '음식 속 성분 설명과 섭취 후 인체 결과를 분리해 확인해야 합니다.',
    checkedAt: '2026-09-23',
    audit: {contentBasis: 'TITLE_AND_PUBLIC_DESCRIPTION', authorityLevel: 'PARTIAL', evidenceLevel: 'C', claimCategories: ['GENERAL_PHYSIOLOGY', 'ORAL_GABA_HUMAN_RESEARCH'], rightsStatus: 'CHECK_REQUIRED', usageMode: 'REVIEW_ONLY', nextAction: '음식 속 GABA와 경구 섭취 연구·개인 효과 주장을 분리'},
  },
  {
    id: 'SHORT-02',
    title: 'GABA와 수면을 연결해 질문하는 영상 후보',
    publicTitle: 'GABA와 수면을 연결해 질문하는 영상 후보',
    publicSummary: '수면과 GABA를 연결해 질문을 던지는 방식의 영상입니다. 이 페이지에서는 원문 확인 전 검토 후보로만 소개합니다.',
    publicPersonSummary: '채널은 화자를 의사로 소개하지만, 이 기록은 인물 확인용이며 영상의 실제 발언·근거·권위를 대신 승인하지 않습니다.',
    publicOperatorSentence: 'GABA와 수면을 연결한 영상 후보이며, 원문·자막·화자·권리 확인 후 일반 교육 자료로 사용할 수 있는지 판단합니다.',
    url: 'https://www.youtube.com/shorts/RLAU1VWGsaI',
    previewImage: 'https://i.ytimg.com/vi/RLAU1VWGsaI/hqdefault.jpg',
    previewAlt: 'GABA와 수면을 연결해 질문하는 영상 후보 미리보기',
    previewLabel: 'YouTube Shorts · 오늘 공유 영상',
    channel: '의학 설명 채널',
    sourceChannelUrl: 'https://www.youtube.com/@doctorLeeTV',
    speaker: '채널 프로필 확인 필요',
    authorityEvidenceUrl: 'https://www.youtube.com/@doctorLeeTV/about',
    summary: 'GABA와 수면의 관계를 질문하는 영상 후보입니다. 영상의 실제 발언과 전체 맥락은 원문 확인이 필요합니다.',
    operatorSentence: 'GABA와 수면을 연결한 영상 후보이며 원문·자막·화자·권리 확인 후 사용 범위를 판단합니다.',
    personSummary: '채널 프로필은 인물 확인에 참고할 수 있으나, 영상의 실제 발언과 연구 근거를 자동 승인하지 않습니다.',
    status: 'HOLD',
    statusReason: '수면과 GABA의 연결이 일반 설명인지 개인 결과를 암시하는지 원문 확인이 필요합니다.',
    checkedAt: '2026-09-22',
    audit: {contentBasis: 'TITLE_AND_PUBLIC_DESCRIPTION', authorityLevel: 'PARTIAL', evidenceLevel: 'C', claimCategories: ['SLEEP_STRESS'], rightsStatus: 'CHECK_REQUIRED', usageMode: 'REVIEW_ONLY', nextAction: '전체 자막에서 수면 관련 표현과 근거·상업 링크를 확인'},
  },
  {
    id: 'SHORT-03',
    title: 'GABA와 신경 신호를 연결해 설명하는 영상 후보',
    publicTitle: 'GABA와 신경 신호를 연결해 설명하는 영상 후보',
    publicSummary: 'GABA를 신경 신호와 연결해 설명하는 방식의 영상입니다. 정확한 내용과 맥락은 원문 확인이 필요합니다.',
    publicPersonSummary: '채널명으로 화자를 소개하고 있으나 실명·학위·소속은 이 기록만으로 확인되지 않았습니다.',
    publicOperatorSentence: 'GABA의 일반 기능을 설명하는 부분이 있는지 원문·자막·화자 확인 후 제한적으로 검토합니다.',
    url: 'https://www.youtube.com/shorts/vnocd9ZVJj0',
    previewImage: 'https://i.ytimg.com/vi/vnocd9ZVJj0/hqdefault.jpg',
    previewAlt: 'GABA와 신경 신호를 연결해 설명하는 영상 후보 미리보기',
    previewLabel: 'YouTube Shorts · 오늘 공유 영상',
    channel: '영양과학 관련 채널',
    sourceChannelUrl: 'https://www.youtube.com/@snack-yang',
    speaker: '채널 프로필 확인 필요',
    summary: 'GABA를 신경 신호와 연결해 설명하는 영상 후보입니다. 정확한 내용과 맥락은 원문 확인이 필요합니다.',
    operatorSentence: '일반 GABA 기능을 설명하는 부분이 있는지 원문·자막·화자 확인 후 제한적으로 검토합니다.',
    personSummary: '화자의 실명·학위·소속은 이 공개 기록만으로 확인되지 않았습니다.',
    status: 'HOLD',
    statusReason: '영상의 화자와 전체 발언 범위를 확인하기 전에는 일반 설명으로 사용할 수 없습니다.',
    checkedAt: '2026-09-22',
    audit: {contentBasis: 'TITLE_AND_PUBLIC_DESCRIPTION', authorityLevel: 'UNVERIFIED', evidenceLevel: 'C', claimCategories: ['GENERAL_PHYSIOLOGY', 'SLEEP_STRESS'], rightsStatus: 'CHECK_REQUIRED', usageMode: 'REVIEW_ONLY', nextAction: '화자 자격·전체 발언·주장 범위를 확인'},
  },
  {
    id: 'SHORT-06',
    title: '경구 GABA와 일반 연구를 질문하는 영상 후보',
    publicTitle: '경구 GABA와 일반 연구를 질문하는 영상 후보',
    publicSummary: '섭취한 GABA가 어떻게 이해되는지를 질문하는 영상 후보입니다. 일반 연구의 조건과 영상의 설명을 따로 비교합니다.',
    publicPersonSummary: '화자의 소속·연구 경력 확인 출처가 있으나, 이는 영상 발언·상업성·특정 결과를 자동 승인하지 않습니다.',
    publicOperatorSentence: '경구 GABA에 관한 영상 설명을 일반 연구의 조건·한계와 대조한 뒤 공개 범위를 판단합니다.',
    url: 'https://www.youtube.com/shorts/rOFkZg09AoY',
    previewImage: 'https://i.ytimg.com/vi/rOFkZg09AoY/hqdefault.jpg',
    previewAlt: '경구 GABA와 일반 연구를 질문하는 영상 후보 미리보기',
    previewLabel: 'YouTube Shorts · 오늘 공유 영상',
    channel: 'SLEEP Dr. 신원철 꿀잠튜브',
    sourceChannelUrl: 'https://www.youtube.com/@sleepdoctor1',
    speaker: '공개 프로필 확인 필요',
    authorityEvidenceUrl: 'https://www.sleepnet.or.kr/workshop/monthly/view?idx=150',
    researchEvidenceUrl: 'https://e-jsm.org/upload/jsm-13-2-60.pdf',
    summary: '섭취한 GABA와 일반 연구의 조건을 질문하는 영상 후보입니다. 영상의 설명과 연구 결과는 따로 비교합니다.',
    operatorSentence: '경구 GABA에 관한 영상 설명을 일반 연구의 조건·한계와 대조한 뒤 공개 범위를 판단합니다.',
    personSummary: '공식 학술 출처는 화자의 소속·연구 경력 확인에 참고할 수 있으나, 영상의 실제 발언·상업성·특정 결과를 자동 승인하지 않습니다.',
    status: 'HOLD',
    statusReason: '안전성 단정이나 개인 결과로 읽히는 표현이 있는지 원문과 연구 조건 확인이 필요합니다.',
    checkedAt: '2026-09-23',
    audit: {contentBasis: 'TITLE_AND_PUBLIC_DESCRIPTION', authorityLevel: 'PARTIAL', evidenceLevel: 'C', claimCategories: ['ORAL_GABA_HUMAN_RESEARCH', 'SLEEP_STRESS'], rightsStatus: 'CHECK_REQUIRED', usageMode: 'REVIEW_ONLY', nextAction: '안전성 단정·복용 권고·이해관계와 경구 연구 조건을 확인'},
  },
  {
    id: 'SHORT-07',
    title: 'GABA와 긴장·뇌 신호를 연결하는 영상 후보',
    publicTitle: 'GABA와 긴장·뇌 신호를 연결하는 영상 후보',
    publicSummary: 'GABA와 긴장·뇌 신호의 관계를 연결해 설명하는 영상 후보입니다. 화자와 실제 발언은 원문 확인이 필요합니다.',
    publicPersonSummary: '공개 설명에서 실제 화자의 이름·학위·면허·소속을 확인하지 못했습니다.',
    publicOperatorSentence: '일반 GABA 기능 설명인지, 개인의 상태나 치료를 말하는지 원문과 자막을 먼저 확인합니다.',
    url: 'https://www.youtube.com/shorts/4MTqi-bapLY',
    previewImage: 'https://i.ytimg.com/vi/4MTqi-bapLY/hqdefault.jpg',
    previewAlt: 'GABA와 긴장·뇌 신호를 연결하는 영상 후보 미리보기',
    previewLabel: 'YouTube Shorts · 오늘 공유 영상',
    channel: '뇌 건강 관련 채널',
    sourceChannelUrl: 'https://www.youtube.com/@vitalize866',
    speaker: '공개 설명에 화자 자격 미기재',
    summary: 'GABA와 긴장·뇌 신호의 관계를 연결해 설명하는 영상 후보입니다. 화자와 실제 발언은 원문 확인이 필요합니다.',
    operatorSentence: '일반 GABA 기능 설명인지 개인의 상태나 치료를 말하는지 원문과 자막을 먼저 확인합니다.',
    personSummary: '실제 화자의 이름·학위·면허·소속을 확인하지 못했습니다.',
    status: 'HOLD',
    statusReason: '화자·자막·근거를 확인하기 전에는 일반 교육 자료로 사용하지 않습니다.',
    checkedAt: '2026-09-22',
    audit: {contentBasis: 'TITLE_AND_PUBLIC_DESCRIPTION', authorityLevel: 'UNVERIFIED', evidenceLevel: 'C', claimCategories: ['GENERAL_PHYSIOLOGY', 'SLEEP_STRESS'], rightsStatus: 'CHECK_REQUIRED', usageMode: 'REVIEW_ONLY', nextAction: '화자·자막·주장 범위와 공개 권리를 확인'},
  },
];

export const SHARED_GABA_VIDEOS = sharedVideos;

// No domestic record has passed the human publication gate yet.
export const DOMESTIC_PUBLIC_GABA_VIDEOS: GabaVideoRecord[] = [];
