export const GABA_MONITOR_SNAPSHOT = {
  "checkedAt": "2026-09-22",
  "sourceChannels": 8,
  "registeredChannels": 8,
  "discoveryQueries": 4,
  "totalDiscoveryQueries": 4,
  "newCandidates": 0,
  "pendingReview": 60,
  "scienceMedicalPriority": 36,
  "videoPriority": 24,
  "autoPublish": 0,
  "humanRoleAssigned": 0,
  "humanRoleTotal": 7,
  "humanSourceReviewed": 0,
  "humanSourceTotal": 5,
  "registeredVideoApproved": 2,
  "registeredVideoTotal": 11,
  "firstMeetingReady": false,
  "triageUrl": "https://github.com/KRAdavid/cellpinda_gaba_sum/blob/main/docs/GABA_VIDEO_TRIAGE.md",
  "reportUrl": "https://github.com/KRAdavid/cellpinda_gaba_sum/blob/main/docs/GABA_VIDEO_DAILY_REPORT.md",
  "kickoffUrl": "https://github.com/KRAdavid/cellpinda_gaba_sum/blob/main/docs/GABA_EDUCATION_KICKOFF.md",
  "sourceRegisterUrl": "https://github.com/KRAdavid/cellpinda_gaba_sum/blob/main/docs/GABA_SOURCE_REGISTER.md"
} as const;
